/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jnitestdemo_Jni */

#ifndef _Included_com_example_jnitestdemo_Jni
#define _Included_com_example_jnitestdemo_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jnitestdemo_Jni
 * Method:    add
 * Signature: ()I
 */JNIEXPORT jint JNICALL Java_com_example_jnitestdemo_Jni_add(JNIEnv *, jobject);
/*
 * Class:     com_example_jnitestdemo_Jni
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */JNIEXPORT jstring JNICALL Java_com_example_jnitestdemo_Jni_getString(JNIEnv *,
		jobject);

#ifdef __cplusplus
}
#endif
#endif
